name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login into Github Container Registry
      run: echo "${{ secrets.CR_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push image to Github Container Registry
      run: |
        docker build . --tag ghcr.io/murf2/latex:1.0
        docker push ghcr.io/murf2/latex:1.0
        docker build . --tag ghcr.io/murf2/latex:latest
        docker push ghcr.io/murf2/latex:latest
